### ISSUE TITLE
ref error

### ISSUE THREAD

**Issue by duydtd97** [arthurdenner/use-lax#126]
![Annotation 2019-11-23 004209](https://user-images.githubusercontent.com/23192661/69447944-1d831800-0d8a-11ea-91c9-a57263f76495.png)

Please help me !

**Comment by arthurdenner** [comment]
Hi @duydtd97!

`useLaxElement` accepts a generic type. Please try:

`const refLax = useLaxElement<HTMLDivElement>();`

Let me know if that doesn't solve it.

**Comment by duydtd97** [comment]
> Hi @duydtd97!
> 
> `useLaxElement` accepts a generic type. Please try:
> 
> `const refLax = useLaxElement<HTMLDivElement>();`
> 
> Let me know if that doesn't solve it.

yes, it solved ! But i dont see Lax working , even your example above https://codesandbox.io/s/039krok5ml

**Comment by arthurdenner** [comment]
@duydtd97, I'm very sorry, I totally forgot to properly update that sandbox. 🤦🏽

You only need `useLaxElement` if your component is added dynamically because you need to manually add it to `lax.js` elements array. Check [this example](https://codesandbox.io/s/q9882qjxzq) and see that it doesn't work if you remove the line 5 and the `ref` prop on line 8.

The way that `lax.js` works now, you need to add the class `lax` to all the elements you want to animate. If you check the sandbox you linked, you'll see how to use it - since I've updated it.

Again, sorry about that and thank you very much for pointing it out!

**Comment by duydtd97** [comment]
@arthurdenner thank for your support ! 

I am looking forward  a new Lax version better than for ReactJS
