### ISSUE TITLE
use-lax breaks when using latest version of lax.js

### ISSUE THREAD

**Issue by dannykeane** [arthurdenner/use-lax#72]
Here's an example:
https://codesandbox.io/s/use-lax-example-xesrj

**Comment by arthurdenner** [comment]
Hi @dannykeane! :wave: 

Thanks for reporting this.

Feel free to investigate and working on it if you want to.

**Comment by arthurdenner** [comment]
@dannykeane, please try the latest version - `3.0.0`.

Please notice that you should add `lax` to the `className` of the components you want to animate instead of `ref` and we are only exporting one hook now and that it should be used on the top level component. This change was necessary since `lax.js` has a new set up.

The README is updated with the changes mentioned above.
